env:
  browser: true
  es2021: true
extends:
  - plugin:markdown/recommended
  - plugin:yaml/recommended
  - plugin:editorconfig/noconflict
  - plugin:jsdoc/recommended
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - airbnb-typescript
  - plugin:prettier/recommended
globals:
  window: true
overrides:
  - files:
      - '*.js'
      - '*.jsx'
    env:
      node: true
    rules:
      '@typescript-eslint/explicit-module-boundary-types': 'off'
      '@typescript-eslint/no-var-requires': 'off'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    impliedStrict: true
    jsx: true
  project: ./tsconfig.json
root: true
rules:
  '@typescript-eslint/consistent-type-imports': warn
  import/extensions:
    - error
    - never
    - tsx: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.config.?s'
  import/order: warn
  no-console:
    - warn
  react/jsx-filename-extension:
    - error
    - extensions:
        - .jsx
        - .tsx
  react/prop-types:
    - 'off'
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
