env:
  browser: true
  es6: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
globals:
  window: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
  - prettier
rules:
  '@typescript-eslint/explicit-function-return-type':
    - 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  no-console:
    - warn
