name: CI on push
on:
  - push
jobs:
  build:
    name: Build and testing production code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 13.x
        uses: actions/setup-node@master
        with:
          node-version: 13.x
      - run: npm ci
      - run: npm run build
      - run: npm test
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
      - build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 13.x
        uses: actions/setup-node@master
        with:
          node-version: 13.x
      - run: npm ci
      - run: npm run build
      - name: deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@master
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
