name: CI on push
on:
  - push
jobs:
  build:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 13.x
        uses: actions/setup-node@master
        with:
          node-version: 13.x
      - run: npm ci
      - run: npm run build
      - run: npm test
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
      - build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 13.x
        uses: actions/setup-node@master
        with:
          node-version: 13.x
      - run: npm ci
      - run: npm run build
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: 'dist'
          target: 'web/vhosts/ikeikechaya.com.staging'
