name: The CI/CD workflow on push the master branch
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  deploy:
    name: Build and tests
    runs-on: ubuntu-latest
    steps:
      - name: Stages the pushed branch
        uses: actions/checkout@v2
      - name: Use the specified version of Node.js
        uses: actions/setup-node@v2
        with:
          cache: ${{ !env.ACT && 'npm' || '' }}
          node-version-file: .node-version
      - name: set npm config
        run: npm config set unsafe-perm true
      - name: Resolve the dependencies
        run: npm ci
      - run: npm run build
      - name: copy files via ssh
        if: ${{ !env.ACT }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: 'dist'
          target: 'web/vhosts/ikeikechaya.com.staging'
      - name: remove the old backup
        if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: rm -rf web/vhosts/ikeikechaya.com.old
      - name: backup
        if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: mv web/vhosts/ikeikechaya.com web/vhosts/ikeikechaya.com.old
      - name: migrate
        if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: mv web/vhosts/ikeikechaya.com.staging/dist web/vhosts/ikeikechaya.com
      - name: teardown
        if: ${{ !env.ACT }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: rm -rf web/vhosts/ikeikechaya.com.staging
